image: "ruby:2.4"

stages:
  - prepare
  - test
  - deploy

# Templates

.ruby_2_4_cache: &ruby_2_4_cache
  cache:
    key: "$CI_COMMIT_REF_NAME-ruby_2_4"
    paths:
      - vendor/bundle

.ruby_2_3_cache: &ruby_2_3_cache
  cache:
    key: "$CI_COMMIT_REF_NAME-ruby_2_3"
    paths:
      - vendor/bundle

.pull_cache: &pull_cache
  cache:
    policy: pull

.push_cache: &push_cache
  cache:
    policy: push

.ruby_2_3: &ruby_2_3
  image: "ruby:2.3"
  <<: *ruby_2_3_cache

.ruby_2_4: &ruby_2_4
  image: "ruby:2.4"
  <<: *ruby_2_4_cache

.test_job: &test_job
  <<: *pull_cache
  variables:
    BUNDLE_PATH: "vendor/bundle"
  stage: test
  environment: testing

.prepare_job: &prepare_job
  <<: *push_cache
  variables:
    BUNDLE_PATH: "vendor/bundle"
  stage: prepare
  script:
    - bundle install -j $(nproc)
  tags:
    - ruby

# Jobs: Prepare

prepare:bundler_2_4:
  <<: *prepare_job
  <<: *ruby_2_4

prepare:bundler_2_3:
  <<: *prepare_job
  <<: *ruby_2_3

# Jobs: Test

test:rubocop:
  <<: *test_job
  <<: *ruby_2_4
  script:
    - bundle exec rubocop
  except:
    - master
    - tags
  tags:
    - ruby

test:rspec_2_3:
  <<: *test_job
  <<: *ruby_2_3
  script:
    - bundle exec rspec
  tags:
    - ruby

test:rspec_2_4:
  <<: *test_job
  <<: *ruby_2_4
  script:
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/
  tags:
    - ruby

# Jobs: deploy

pages:
  stage: deploy
  dependencies:
    - test:rspec_2_4
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master@exacting/justimmo_client

deploy:rubygems:
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=rubygems --api-key=$RUBYGEMS_API_KEY
  only:
    - tags@exacting/justimmo_client
