image: 'ruby:2.3'

.test_job: &test_job
  environment: testing
  cache:
    paths:
      - cache/bundler
  before_script:
    - bundle install --without development -j $(nproc) --path=cache/bundler
  tags:
    - ruby

test:rubocop:
  <<: *test_job
  script: bundle exec rubocop
  only:
    - dev

test:rspec:
  <<: *test_job
  script: bundle exec rspec
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - test:rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

deploy:rubygems:
  stage: deploy
  dependencies:
    - test:rspec
  before_script:
    - gem install dpl
  script:
    - dpl --provider=rubygems --api-key=$RUBYGEMS_API_KEY
  only:
    - tag
